apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: python-test
  namespace: cicd
spec:
  workspaces:
    - name: source
  steps:
    - name: unit-test
      image: 10.0.0.41/library/python:3.11-slim
      workingDir: $(workspaces.source.path)/source
      env:
        - name: PYTHONPATH          # ← 加这几行
          value: $(workspaces.source.path)/source
      script: |
        #!/bin/sh
        set -eux
        pip install --no-cache-dir -r requirements-dev.txt
        pytest -q
