apiVersion: v1
kind: Secret
metadata:
  name: gitlab-auth
  namespace: cicd
  annotations:
    tekton.dev/git-0: http://10.0.0.200
type: kubernetes.io/basic-auth
stringData:
  username: root
  password: <GITLAB_TOKEN_OR_PASSWORD>
