apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: tekton-demo-cicd-run-
  namespace: cicd
spec:
  taskRunTemplate:
    serviceAccountName: pipeline
  pipelineRef:
    name: tekton-demo-cicd
  params:
    - name: repo-url
      value: http://10.0.0.200/root/teketondemo.git
    - name: git-revision
      value: main
    - name: image-repo
      value: 10.0.0.41/library/tekton-demo-api
    - name: image-tag
      value: manual-001
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: tekton-demo-workspace-pvc
