apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: tekton-demo-template
  namespace: cicd
spec:
  params:
    - name: gitrevision
      default: main
    - name: gitrepositoryurl
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: tekton-demo-triggered-
        namespace: cicd
      spec:
        taskRunTemplate:
          serviceAccountName: pipeline
        pipelineRef:
          name: tekton-demo-cicd
        params:
          - name: repo-url
            value: $(tt.params.gitrepositoryurl)
          - name: git-revision
            value: $(tt.params.gitrevision)
          - name: image-repo
            value: 10.0.0.41/library/tekton-demo-api
          - name: image-tag
            value: $(uid)
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes: ["ReadWriteOnce"]
                storageClassName: nfs-sc
                resources:
                  requests:
                    storage: 2Gi
